name: SussyDB GitHub Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: mkdir db
    - run: mkdir db/admin
    - run: mkdir db/test
    - run: echo "[]" >> db/admin/admin.json
    - run: echo "[]" >> db/test/test.json
    - run: echo '[{"name":"port","value":6942},{"name":"name","value":"SussyDB"}]' >> sussysettings.json
    - run: npm ci
    - run: npm test
